name: Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Vendor dependencies
        run: cargo vendor
      - name: Create cargo config
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << 'EOF'
          [source.crates-io]
          replace-with = "vendored-sources"

          [source.vendored-sources]
          directory = "vendor"
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: decap-oauth:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test Docker image
        run: |
          docker run -d --name test-container \
            -e OAUTH_CLIENT_ID=test \
            -e OAUTH_SECRET=test \
            -e OAUTH_ORIGINS=localhost \
            -p 3005:3005 \
            decap-oauth:test
          sleep 5
          curl -f http://localhost:3005/auth?provider=github || exit 1
          docker logs test-container
          docker stop test-container
